# .github/workflows/ci.yml

name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install Poetry
      run: pip install poetry

    - name: Install dependencies
      run: poetry install --no-root --sync

    - name: Run tests
      run: |
        # Run tests with pytest
        poetry run pytest --maxfail=1 --disable-warnings -q

    - name: Lint code
      run: |
        # Run flake8 for linting
        poetry run flake8 .
        # Run black for formatting
        poetry run black --check .
        # Run isort for import sorting
        poetry run ruff check .
